<?php
/**
 * mwp phpMyAdmin router — single-use magic-link dispatcher.
 *
 * Loaded by phpMyAdmin via /etc/phpmyadmin/conf.d/mwp-router.php.
 * Reads link files in /etc/mwp/pma-links/*.php, matches the request URL
 * against each link's path prefix, and on match:
 *   1. enforces 24h TTL,
 *   2. binds the link to the first browser that hits it (single-use),
 *   3. injects autologin credentials into $cfg['Servers'][1].
 *
 * Single-use binding works via a per-link HttpOnly cookie. First request
 * has no cookie -> we generate a token, persist it back to the link file
 * as `claimed_token`, and Set-Cookie. Subsequent requests must present
 * the cookie or get HTTP 403.
 *
 * Generated by mwp pma_install. Do not edit by hand — regenerated on
 * `mwp db pma install`.
 */

if (defined('MWP_PMA_ROUTED')) return;
define('MWP_PMA_ROUTED', true);

$mwp_links_dir = '/etc/mwp/pma-links';
if (!is_dir($mwp_links_dir)) return;

$req_uri = $_SERVER['REQUEST_URI'] ?? '';
$req_path = parse_url($req_uri, PHP_URL_PATH);
if (!is_string($req_path) || $req_path === '') return;

foreach (glob("$mwp_links_dir/*.php") as $link_file) {
    $link = @include $link_file;
    if (!is_array($link) || empty($link['path'])) continue;

    // Only process the link whose path prefix matches this request
    if (strpos($req_path, $link['path']) !== 0) continue;

    // Hard expiry — defense in depth (sweeper cron also clears expired links)
    if (!empty($link['expires']) && time() > (int) $link['expires']) {
        @unlink($link_file);
        http_response_code(410);
        header('Content-Type: text/plain');
        die("mwp-pma: link expired. Generate a new one: mwp db pma {$link['domain']}\n");
    }

    // Single-use cookie name — derived from path so links don't collide
    $cookie_name = 'mwp_pma_lock_' . substr(md5($link['path']), 0, 12);
    $bound = isset($link['claimed_token']) ? (string) $link['claimed_token'] : '';
    $browser_token = isset($_COOKIE[$cookie_name]) ? (string) $_COOKIE[$cookie_name] : '';

    if ($bound === '') {
        // First hit — claim the link for this browser session
        try {
            $token = bin2hex(random_bytes(24));
        } catch (Exception $e) {
            $token = bin2hex(openssl_random_pseudo_bytes(24));
        }
        $link['claimed_token'] = $token;
        $link['claimed_at'] = time();
        $link['claimed_ip'] = $_SERVER['REMOTE_ADDR'] ?? '';

        // Persist atomically — var_export round-trips arrays cleanly
        $payload = "<?php return " . var_export($link, true) . ";\n";
        $tmp = $link_file . '.tmp.' . getmypid();
        if (@file_put_contents($tmp, $payload, LOCK_EX) !== false) {
            @chmod($tmp, 0600);
            @rename($tmp, $link_file);
        }

        setcookie($cookie_name, $token, [
            'expires'  => (int) ($link['expires'] ?? 0),
            'path'     => $link['path'],
            'httponly' => true,
            'secure'   => !empty($_SERVER['HTTPS']),
            'samesite' => 'Lax',
        ]);
    } else {
        // Already claimed — must present matching cookie
        if (!hash_equals($bound, $browser_token)) {
            http_response_code(403);
            header('Content-Type: text/plain');
            die("mwp-pma: this link is locked to another browser session.\n"
              . "Generate a fresh link: mwp db pma {$link['domain']}\n");
        }
    }

    // Apply autologin for this site — pma reads $cfg after this file returns.
    // AllowRoot is gated by the link's allow_root flag: per-site links keep it
    // false (defense in depth), admin links flip it true so root can sign in.
    $cfg['Servers'][1]['auth_type']        = 'config';
    $cfg['Servers'][1]['user']             = $link['user'];
    $cfg['Servers'][1]['password']         = $link['pass'];
    $cfg['Servers'][1]['host']             = 'localhost';
    $cfg['Servers'][1]['only_db']          = $link['db_name'] ?? '';
    $cfg['Servers'][1]['verbose']          = $link['domain'] ?? '';
    $cfg['Servers'][1]['AllowNoPassword']  = false;
    $cfg['Servers'][1]['AllowRoot']        = !empty($link['allow_root']);

    return;
}
